// Site content is static in index.html (SEO: the crawler must see real copy,
// not an empty shell). Only runtime configuration lives here.

// Bump when frame/video CONTENT changes at the same URLs — busts long-lived
// browser/CDN caches (frames and videos are served with max-age=86400).
export const MEDIA_VERSION = 2

// Hero frame sequences (regenerated by scripts/extract-hero-frames.mjs)
export const FRAMES = {
  desktop: { dir: '/frames/desktop', count: 193, width: 1440, height: 810 },
  mobile: { dir: '/frames/mobile', count: 97, width: 720, height: 405 },
}
